version: '3.8.10'
services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./beautiHub:/beautiHub

  db:
    image: mysql:8
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django_db
      MYSQL_USER: aakash
      MYSQL_PASSWORD: aakash@123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8080:80
volumes:
  db_data: