version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./beautiHub:/beautiHub
    environment:
      - DJANGO_SETTINGS_MODULE=beautiHub.settings
    depends_on:
      - db
    restart: always
    networks:
      - beautihub_monitoring

  db:
    image: mysql:8
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django_db
      MYSQL_USER: aakash
      MYSQL_PASSWORD: aakash@123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - beautihub_monitoring

  mysql_exporter:
    image: prom/mysqld-exporter  # Use the official MySQL exporter image
    volumes:
      - ./.my.cnf:/cfg/.my.cnf
    command:
      - '--config.my-cnf=/cfg/.my.cnf'
      - '--mysqld.address=db:3306'
    # environment:
    #   DATA_SOURCE_NAME: root:aakash@123@tcp(db:3306)/django_db  # Replace with credentials and hostname
    ports:
      - "9104:9104"  # Map container port 9104 to host port 9104 (or a different port if needed)
    networks:
      - beautihub_monitoring 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8080:80"
    networks:
      - beautihub_monitoring

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - app
      - mysql_exporter
    networks:
      - beautihub_monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    networks:
      - beautihub_monitoring


networks:
  beautihub_monitoring:
    external: true

volumes:
  db_data:
  grafana_data:
