# Global configuration
global:
  scrape_interval: 15s  # How often Prometheus scrapes targets (every 15 seconds)

# Scrape configs
scrape_configs:

  # Scrape config for Django application (assuming metrics exposed on port 8000)
  - job_name: 'django'
    static_configs:
      - targets: ['app:8000']  # Replace 'app' with your Django service name if different
    metrics_path: /metrics

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']  # Replace 'grafana' with your Grafana service name if different

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql_exporter:9104']

  # # Scrape config for MySQL database (assuming metrics exposed on port 3306)
  # - job_name: 'mysql'
  #   static_configs:
  #     - targets: ['db:3306']  # Replace 'db' with your database service name if different

  # Scrape config for Grafana (if it exposes Prometheus metrics)
 
# Alertmanager configuration (commented out as not included in your docker-compose)
# alerting:
#   alertmanagers:
#     - static_configs:
#       - targets: ['localhost:9093']
