# Generated by Django 4.2.1 on 2023-05-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image_url', models.FileField(upload_to='upload/')),
                ('entity_id', models.IntegerField(max_length=11)),
                ('entity_code', models.CharField(max_length=100)),
                ('is_deleted', models.IntegerField(max_length=11)),
            ],
        ),
    ]
