# Generated by Django 4.1.7 on 2023-06-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='entity_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='is_deleted',
            field=models.IntegerField(),
        ),
    ]
